Revert "Bump oursql version to 0.9.3.2"
This reverts commit b9f7c1fcd26003aa7df46a1a8a19c883239efd8e.

I can't get oursql 0.9.3.2 to build:
18:57:48 {:timestamp=>"2019-04-04T18:57:48.970840-0700", :message=>"oursqlx/_exceptions.c:621:15: error: 'for' loop initial declarations are only allowed in C99 mode", :level=>:info}

There appears to be an unmerged patch :(
https://github.com/python-oursql/oursql/pull/15/commits/b4683ed4c9ef8fa6dc78da159f481f75ff0f657b

In any case, we are on 0.9.3.1 and haven't seemed to have any problems.
There seem to be no code changes made to this repo since the last build.